export type ElementCardRarity = "common" | "rare" | "legendary";
export type ElementCardElement =
  | "fire"
  | "water"
  | "earth"
  | "air"
  | "void"
  | "lightning";

export interface ElementCard {
  id: string;
  name: string;
  element: ElementCardElement;
  symbol: string;
  power: string;
  description: string;
  rarity: ElementCardRarity;
  color: string;
}

export const ELEMENT_CARDS: ElementCard[] = [
  {
    id: "fire-mastery",
    name: "Fire Mastery",
    element: "fire",
    symbol: "🔥",
    power: "+2s per match",
    description: "Your flames grow stronger with every sort",
    rarity: "common",
    color: "oklch(0.65 0.25 40)",
  },
  {
    id: "flame-shield",
    name: "Flame Shield",
    element: "fire",
    symbol: "🛡️",
    power: "Block 1 game over",
    description: "A fiery barrier protects you once from defeat",
    rarity: "rare",
    color: "oklch(0.58 0.22 30)",
  },
  {
    id: "inferno-surge",
    name: "Inferno Surge",
    element: "fire",
    symbol: "💥",
    power: "Clear random shelf",
    description: "Unleash an inferno on your most stubborn shelf",
    rarity: "rare",
    color: "oklch(0.6 0.24 35)",
  },
  {
    id: "phoenix-rise",
    name: "Phoenix Rise",
    element: "fire",
    symbol: "🦅",
    power: "Revive on fail",
    description: "Rise from the ashes of defeat — once",
    rarity: "legendary",
    color: "oklch(0.7 0.22 45)",
  },
  {
    id: "water-flow",
    name: "Water Flow",
    element: "water",
    symbol: "💧",
    power: "+10s freeze bonus",
    description: "Time flows like water through your fingers",
    rarity: "common",
    color: "oklch(0.55 0.2 230)",
  },
  {
    id: "ocean-calm",
    name: "Ocean Calm",
    element: "water",
    symbol: "🌊",
    power: "Slow timer 50%",
    description: "The deep ocean slows all things around you",
    rarity: "rare",
    color: "oklch(0.5 0.18 240)",
  },
  {
    id: "tidal-wave",
    name: "Tidal Wave",
    element: "water",
    symbol: "🌀",
    power: "Shuffle any shelf",
    description: "A tidal force rearranges tiles to your will",
    rarity: "rare",
    color: "oklch(0.52 0.2 245)",
  },
  {
    id: "frost-touch",
    name: "Frost Touch",
    element: "water",
    symbol: "❄️",
    power: "Freeze a shelf",
    description: "Lock a shelf in ice until the moment is right",
    rarity: "legendary",
    color: "oklch(0.72 0.15 220)",
  },
  {
    id: "earth-strength",
    name: "Earth Strength",
    element: "earth",
    symbol: "🪨",
    power: "+1 shelf capacity",
    description: "Stone walls hold far more than you expect",
    rarity: "common",
    color: "oklch(0.5 0.14 100)",
  },
  {
    id: "stone-wall",
    name: "Stone Wall",
    element: "earth",
    symbol: "🏔️",
    power: "Block 2 bad moves",
    description: "Nothing passes through solid earth unpunished",
    rarity: "rare",
    color: "oklch(0.45 0.12 95)",
  },
  {
    id: "root-bind",
    name: "Root Bind",
    element: "earth",
    symbol: "🌱",
    power: "Pin matching items",
    description: "Ancient roots hold your matched tiles in place",
    rarity: "rare",
    color: "oklch(0.55 0.16 130)",
  },
  {
    id: "crystal-form",
    name: "Crystal Form",
    element: "earth",
    symbol: "💎",
    power: "Double gem clears",
    description: "Earth pressure creates perfect crystalline power",
    rarity: "legendary",
    color: "oklch(0.6 0.18 155)",
  },
  {
    id: "air-speed",
    name: "Air Speed",
    element: "air",
    symbol: "💨",
    power: "+1 match maker",
    description: "Swift as the wind, matches appear before you",
    rarity: "common",
    color: "oklch(0.72 0.12 215)",
  },
  {
    id: "wind-dash",
    name: "Wind Dash",
    element: "air",
    symbol: "🌬️",
    power: "Move any 2 items",
    description: "The wind carries tiles exactly where you need",
    rarity: "rare",
    color: "oklch(0.68 0.1 220)",
  },
  {
    id: "thunder-call",
    name: "Thunder Call",
    element: "air",
    symbol: "⚡",
    power: "+5s on each match",
    description: "Each match calls a crackling bolt of lightning",
    rarity: "rare",
    color: "oklch(0.75 0.2 80)",
  },
  {
    id: "storm-eye",
    name: "Storm Eye",
    element: "air",
    symbol: "🌪️",
    power: "Skip 1 timer tick",
    description: "Inside the storm's eye, time briefly stands still",
    rarity: "legendary",
    color: "oklch(0.65 0.15 225)",
  },
  {
    id: "void-shift",
    name: "Void Shift",
    element: "void",
    symbol: "🕳️",
    power: "Remove any 3 items",
    description: "The void absorbs what you no longer need",
    rarity: "legendary",
    color: "oklch(0.35 0.08 280)",
  },
  {
    id: "solar-flare",
    name: "Solar Flare",
    element: "lightning",
    symbol: "☀️",
    power: "+15s bonus time",
    description: "Solar energy charges your timers with raw power",
    rarity: "rare",
    color: "oklch(0.82 0.2 80)",
  },
  {
    id: "lunar-pull",
    name: "Lunar Pull",
    element: "void",
    symbol: "🌙",
    power: "Auto-sort 1 match",
    description: "Moonlight aligns your matching tiles perfectly",
    rarity: "rare",
    color: "oklch(0.6 0.1 270)",
  },
  {
    id: "star-dust",
    name: "Star Dust",
    element: "lightning",
    symbol: "✨",
    power: "+1 hammer charge",
    description: "Stardust condenses into unstoppable raw power",
    rarity: "legendary",
    color: "oklch(0.85 0.15 85)",
  },
];
