/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getCurrentLevel' : IDL.Func([], [IDL.Nat], ['query']),
  'getProgress' : IDL.Func(
      [],
      [
        IDL.Record({
          'bestMoves' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
          'currentLevel' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'saveProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getCurrentLevel' : IDL.Func([], [IDL.Nat], ['query']),
    'getProgress' : IDL.Func(
        [],
        [
          IDL.Record({
            'bestMoves' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
            'currentLevel' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'saveProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };