/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'earnCard' : IDL.Func([IDL.Text], [], []),
  'getCardAlbum' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getProgress' : IDL.Func(
      [],
      [
        IDL.Record({
          'bestTimes' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
          'collectedCards' : IDL.Vec(IDL.Text),
          'inventory' : IDL.Record({
            'matchMakers' : IDL.Nat,
            'hammers' : IDL.Nat,
            'timeFreezers' : IDL.Nat,
          }),
          'winStreak' : IDL.Nat,
          'firstUnbeatenLevel' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'resetWinStreak' : IDL.Func([], [], []),
  'saveProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateInventory' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateWinStreak' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'earnCard' : IDL.Func([IDL.Text], [], []),
    'getCardAlbum' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getProgress' : IDL.Func(
        [],
        [
          IDL.Record({
            'bestTimes' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
            'collectedCards' : IDL.Vec(IDL.Text),
            'inventory' : IDL.Record({
              'matchMakers' : IDL.Nat,
              'hammers' : IDL.Nat,
              'timeFreezers' : IDL.Nat,
            }),
            'winStreak' : IDL.Nat,
            'firstUnbeatenLevel' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'resetWinStreak' : IDL.Func([], [], []),
    'saveProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateInventory' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updateWinStreak' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };